### ISSUE TITLE
Support RN > 0.47

### ISSUE THREAD

**Issue by kontinuity** [vikeri/react-native-background-job#47]
React-native 0.47 has breaking changes which means we have to remove override from a method. Change commit at https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8

**Comment by vikeri** [comment]
Should be fixed by: https://github.com/vikeri/react-native-background-job/pull/46

Can you confirm by downloading `2.0.0`?

**Comment by syardumi** [comment]
I can confirm this still is not working on RN 0.48 with RNBJ 2.0.0.

`./node_modules/react-native-background-timer/android/src/main/java/com/ocetnik/timer/BackgroundTimerPackage.java:26: error: method does not override or implement a method from a supertype
    @Override`

**Comment by syardumi** [comment]
I can confirm the fix in 2.0.0. (Sorry for last message; wasn't looking at the file path signatures)

**Comment by vikeri** [comment]
Great!
