### ISSUE TITLE
Don't work with rn >= 0.44.3 

### ISSUE THREAD

**Issue by ophite** [vikeri/react-native-background-job#30]

**Comment by spyworldxp** [comment]
```
:react-native-background-job:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/project/sms2/node_modules/react-native-background-job/android/src/main/java/com/pilloxa/backgroundjob/BackgroundJobModule.java:22: error: cannot find symbol
import static com.facebook.react.common.ApplicationHolder.getApplication;
                                       ^
  symbol:   class ApplicationHolder
  location: package com.facebook.react.common
/project/sms2/node_modules/react-native-background-job/android/src/main/java/com/pilloxa/backgroundjob/BackgroundJobModule.java:22: error: static import only from classes and interfaces
import static com.facebook.react.common.ApplicationHolder.getApplication;
^
/project/sms2/node_modules/react-native-background-job/android/src/main/java/com/pilloxa/backgroundjob/BackgroundJobModule.java:253: error: cannot find symbol
                ((ReactApplication) getApplication())
                                    ^
  symbol:   method getApplication()
  location: class BackgroundJobModule
3 errors
:react-native-background-job:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-background-job:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by capozzid** [comment]
Same problem with RN 0.45

**Comment by toteto** [comment]
@ophite @spyworldxp @capozzid 
If you could go and check https://github.com/vikeri/react-native-background-job/pull/38 if my fork fixes your problem. The example app is working with RN 0.45 so it should be fine.

**Comment by vikeri** [comment]
I think I have a fix running, please try the beta version: "react-native-background-job@1.2.4-0"

**Comment by millerbennett** [comment]
> I think I have a fix running, please try the beta version: "react-native-background-job@1.2.4-0"

This resolved the compilation error on my end.

**Comment by ManuelThomas** [comment]
react-native-background-job@1.2.4-0 says it requires min SDK 21

**Comment by vikeri** [comment]
@ManuelThomas Yes that is correct: https://github.com/vikeri/react-native-background-job#requirements
